version: '3.6'
services:
  maze-runner:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.maze-runner
      target: maze-runner
    environment:
      VERBOSE:
      DEBUG:
    networks:
      default:
        aliases:
          - maze-runner
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./features:/app/features

networks:
  default:
    name: ${BUILDKITE_JOB_ID:-source-maps-maze-runner}
