steps:

  - label: 'Packager'
    key: "packager"
    timeout_in_minutes: 3
    plugins:
      - docker-compose#v3.7.0:
          build: packager
          image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/source-maps
          cache-from:  packager:855461928731.dkr.ecr.us-west-1.amazonaws.com/source-maps:packager-${BRANCH_NAME}
      - docker-compose#v3.7.0:
          push: packager:855461928731.dkr.ecr.us-west-1.amazonaws.com/source-maps:packager-${BRANCH_NAME}
      - docker-compose#v3.7.0:
          run: packager
    artifact_paths: build/bugsnag-source-maps.tgz

  - label: 'Maze Runner image'
    key: "run-maze"
    depends_on: "packager"
    timeout_in_minutes: 20
    plugins:
      - artifacts#v1.3.0:
          download:
            from: build/bugsnag-source-maps.tgz
            to: bugsnag-source-maps.tgz
      - docker-compose#v3.7.0:
          use-aliases: true
          run: maze-runner

#  - label: 'Browser end-to-end tests'
#    depends_on: "package"
#    timeout_in_minutes: 20
#    skip: Placeholder step - will be Maze Runner
#    command: echo
#
#  - label: 'Node end-to-end tests'
#    depends_on: "package"
#    timeout_in_minutes: 20
#    skip: Placeholder step - will be Maze Runner
#    command: echo
#
#  - label: 'React Native 0.60 end-to-end tests'
#    depends_on: "package"
#    timeout_in_minutes: 20
#    skip: Placeholder step - will be Maze Runner
#    command: echo
#
#  - label: 'React Native 0.61 end-to-end tests'
#    depends_on: "package"
#    timeout_in_minutes: 20
#    skip: Placeholder step - will be Maze Runner
#    command: echo
#
#  - label: 'React Native 0.62 end-to-end tests'
#    depends_on: "package"
#    timeout_in_minutes: 20
#    skip: Placeholder step - will be Maze Runner
#    command: echo
#
#  - label: 'React Native 0.63 end-to-end tests'
#    depends_on: "package"
#    timeout_in_minutes: 20
#    skip: Placeholder step - will be Maze Runner
#    command: echo
