steps:
  - label: 'React Native 0.60 end-to-end tests'
    timeout_in_minutes: 20
    skip: Placeholder step - will be Maze Runner
    command: echo

  - label: 'React Native 0.61 end-to-end tests'
    timeout_in_minutes: 20
    skip: Placeholder step - will be Maze Runner
    command: echo

  - label: 'React Native 0.62 end-to-end tests'
    timeout_in_minutes: 20
    skip: Placeholder step - will be Maze Runner
    command: echo

  - label: 'React Native 0.63 end-to-end tests'
    timeout_in_minutes: 20
    skip: Placeholder step - will be Maze Runner
    command: echo

  - label: 'Browser end-to-end tests'
    timeout_in_minutes: 20
    skip: Placeholder step - will be Maze Runner
    command: echo

  - label: 'Node end-to-end tests'
    timeout_in_minutes: 20
    skip: Placeholder step - will be Maze Runner
    command: echo
