steps:

  - label: 'Packager'
    key: "packager"
    timeout_in_minutes: 3
    plugins:
      - docker-compose#v3.7.0:
          build: packager
          image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/source-maps
          cache-from:  packager:855461928731.dkr.ecr.us-west-1.amazonaws.com/source-maps:packager-${BRANCH_NAME}
      - docker-compose#v3.7.0:
          push: packager:855461928731.dkr.ecr.us-west-1.amazonaws.com/source-maps:packager-${BRANCH_NAME}
      - docker-compose#v3.7.0:
          run: packager
    artifact_paths: build/bugsnag-source-maps.tgz

  - label: 'Run Maze Runner tests'
    key: "run-maze"
    depends_on: "packager"
    timeout_in_minutes: 20
    env:
      DEBUG: true
    plugins:
      - artifacts#v1.3.0:
          download: build/bugsnag-source-maps.tgz
      - docker-compose#v3.7.0:
          use-aliases: true
          run: maze-runner
